version: '3.8'
services:
  db:
    image: postgres:14-alpine
    container_name: melorec-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=melorec_db
    volumes:
      - melorec_db_data:/var/lib/postgresql/data

volumes:
  melorec_db_data: